# Generated by Django 5.1.4 on 2025-01-07 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoparsed_address_field", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_id",
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line_1",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address Line 1"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address Line 2"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="formatted",
            field=models.TextField(
                blank=True, null=True, verbose_name="Formatted Address"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="address",
            name="locality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addresses",
                to="autoparsed_address_field.locality",
                verbose_name="Locality",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude"),
        ),
        migrations.AlterField(
            model_name="address",
            name="raw",
            field=models.TextField(blank=True, null=True, verbose_name="Raw Address"),
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                help_text="ISO 3166-1 alpha-2 or alpha-3 codes",
                max_length=3,
                unique=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="locality",
            name="name",
            field=models.CharField(max_length=165, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="locality",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Postal Code"
            ),
        ),
        migrations.AlterField(
            model_name="locality",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="localities",
                to="autoparsed_address_field.state",
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="code",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Code"
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="autoparsed_address_field.country",
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(max_length=165, verbose_name="Name"),
        ),
    ]
